TileDB-Inc/TileDB-BioImaging

examples/OMETiff-convertor-demo.ipynb, examples/OMEZarr-convertor-demo.ipynb, tests/__init__.py, tests/integration/converters/test_ome.py, tests/unit/converters/test_ome_tiff.py, tests/unit/converters/test_ome_zarr.py, tests/unit/converters/test_openslide.py, tests/unit/test_openslide.py, tiledbimg/converters/base.py, tiledbimg/converters/ome_tiff.py, tiledbimg/converters/ome_zarr.py, tiledbimg/converters/openslide.py, tiledbimg/openslide.py
`level_downsamples` is [derived](https://github.com/openslide/openslide/blob/dd3a152250b460860614a3a793309245eebbcb7c/src/openslide.c#L285-L287) from `level_dimensions`, therefore it can be computed at runtime instead of being stored as metadata at ingestion time.
=> Change level_downsamples from stored attribute to computed property

tiledbimg/converters/base.py
This conditionalizes the relative group member on non TileDB Cloud URIs.
=> Support TileDB-Cloud group member add

tests/integration/converters/test_ome_tiff.py, tiledbimg/converters/base.py, tiledbimg/converters/ome_tiff.py
The `tifffile` package has several image-like classes that expose an `asarray()` method (`TiffPageSeries`, `TiffPage`, `TiffFrame`, etc.). On https://github.com/TileDB-Inc/TileDB-BioImaging/pull/20 `OMETiffReader._tiff_series` (`TiffPageSeries` instances) was replaced by `_pages` (`TiffPage` instances) but that turned out to be a mistake. We should serialize each image as a [level](https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tests/test_tifffile.py#L16312), not [keyframe](https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tests/test_tifffile.py#L16310); the latter is (apparently) needed only for the metadata of the image.
=> OMETiffReader fix: 'levels' should be TiffPageSeries, not TiffPage instances

tests/__init__.py, tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tests/unit/test_openslide.py, tiledbimg/converters/base.py, tiledbimg/converters/ome_tiff.py, tiledbimg/openslide.py
Misc. metadata fixes and improvements based on real-world TIFF files:
- Ignore missing OME-XML metadata
- Drop the `original_filename` metadata key; YAGNI
- Handle properly axes transformations (swapaxes, moveaxis) for any 3D image
- A more general and elegant solution to this problem will be addressed in a separate PR.
- Store image level in metadata (instead of trying to infer it from the uri).
=> Metadata tweaks

tests/__init__.py, tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tests/unit/converters/test_ome_zarr.py, tests/unit/converters/test_openslide.py, tiledbimg/converters/base.py, tiledbimg/converters/ome_tiff.py, tiledbimg/converters/ome_zarr.py, tiledbimg/converters/openslide.py, tiledbimg/openslide.py
First PR towards supporting any NGFF compatible 2 to 5 dimensional image data; more to follow.
This PR still supports only 3D images but changes the order of dimensions from the current `XYC` (width, height, channel) to `CYX`. This is the canonical dimension order of multichannel images (the full canonical order for 5D data is `TCZYX`).
Additionally, `TileDBOpenSlide.read_region` changed to return a 3D numpy array in `YXC` order instead of `XYC` in order to be consistent with the Numpy ([as opposed to PIL](https://stackoverflow.com/questions/57259519/handling-height-width-vs-width-height-coordinate-order-in-pil-vs-ndarray)) convention.
**Note**: backwards incompatible change.
=> Change dimension order from XYC to CYX

.pre-commit-config.yaml, setup.py, tests/unit/test_axes.py, tiledbimg/converters/axes.py, tiledbimg/converters/base.py, tiledbimg/converters/ome_tiff.py, tiledbimg/converters/ome_zarr.py, tiledbimg/converters/openslide.py
Second PR towards supporting any NGFF compatible 2 to 5 dimensional image data; follow-up to https://github.com/TileDB-Inc/TileDB-BioImaging/pull/26.
This PR:
- Moves the swap/move axes logic (currently hardcoded in the various converters) to a new `tiledbimg.converters.axes` module
- Generalizes this logic to support transforming from an arbitrary axes sequence to a canonical axes sequence. Ideally the transformation uses the minimal number of transpositions, although this is unproven; the current algorithm just picks greedily the transposition that minimizes the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) between the input and the target sequence.
=> Support general axes transpositions

tiledbimg/converters/base.py, tiledbimg/converters/ome_tiff.py, tiledbimg/converters/ome_zarr.py, tiledbimg/converters/openslide.py
- Refactor `ImageWriter` and `ImageConverter.from_tiledb` (and at a lesser degree `ImageReader` and `ImageConverter.to_tiledb`).
- Change the OME-Zarr stored metadata from pickle to json.
=> Refactor ImageWriter/ImageConverter.from_tiledb

tests/__init__.py, tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tiledbimg/converters/base.py, tiledbimg/converters/ome_tiff.py, tiledbimg/converters/ome_zarr.py, tiledbimg/converters/openslide.py
It's not the responsibility of the library to parallelize a given function (or functions); this can (and should) be done by the library user if desired.
=> Drop ImageReader.convert_images

.github/workflows/release.yml
According to [that](https://github.com/pypa/gh-action-pypi-publish/commit/9b8e7336db3f96a2939a3e9fa827c62f466ca60d) `@master` should change to `release/v1`
=> Hotfix PYPI publish repository tag

README.md, examples/OMETiff-convertor-demo.ipynb, examples/OMEZarr-convertor-demo.ipynb, tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/converters/ome_zarr.py, tiledb/bioimg/converters/openslide.py
`ImageConverter` (and its subclasses) instances have minimal state (actually zero after https://github.com/TileDB-Inc/TileDB-BioImaging/pull/38). This PR changes its methods (`to_tiledb`, `from_tiledb`) to classmethods.
=> Refactor ImageConverter

tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tests/unit/test_openslide.py, tiledb/bioimg/openslide.py
- Change `TileDBOpenSlide.__init__` to accept (open) TileDB image level arrays instead of opening & closing them on every `read_region` call.
-  Make `TileDBOpenSlide` a context manager for closing the image level arrays in a clean manner:
```py
with TileDBOpenSlide.from_group_uri(uri) as t:
...
```
=> TileDBOpenSlide context manager

setup.py, tests/unit/test_axes.py, tiledb/bioimg/converters/axes.py, tiledb/bioimg/openslide.py
Replace [Levenshtein](https://pypi.org/project/Levenshtein/) (GPL) with ~[edit-operation](https://pypi.org/project/edit-operation/)~ [pyeditdistance](https://pypi.org/project/pyeditdistance/) (MIT). 
Note: Unlike `Levenshtein` that can compare arbitrary sequences, `edit-operation` can compare only strings, so the `Transpose` API and related functions were adjusted accordingly.
=> Replace Levenshtein dependency

.github/workflows/ci.yml, tests/__init__.py, tests/integration/converters/test_ome_tiff.py, tiledb/bioimg/converters/ome_tiff.py
The `CMU-1-Small-Region.ome.tiff` test file generated by [raw2ometiff](https://github.com/glencoesoftware/raw2ometiff) had [non-standard tile dimensions](https://github.com/glencoesoftware/raw2ometiff/issues/88), which required a workaround in `OMETiffWriter`  to ignore such tiles. This has since been [resolved](https://github.com/glencoesoftware/raw2ometiff/pull/89).
This PR replaces the previous  `CMU-1-Small-Region.ome.tiff` with a well-formed one and removes the workaround for malformed tiff files. While at it, the support for reading test files from S3 is also removed as it's not needed anymore.
=> Remove workaround for malformed tiff files

setup.py, tiledb/bioimg/converters/ome_tiff.py
Caveats: 
1. The json-deserialized metadata are not identical to the original. In particular I found two type changes:
- Enumeration fields (e.g. `photometric`, `planarconfig`, `resolutionunit`): deserialized to integers.
- Tuples (e.g. `extrasamples`, `tile`, `resolution`): deserialized to lists
AFAICT neither of these differences affect the behavior of `TiffWriter.write`
2. There is no guarantee that all metadata will continue being json-serializable in the future.
=> Replace pickle with json for OME-TIFF metadata

tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tests/unit/test_axes.py, tests/unit/test_tiles.py, tiledb/bioimg/converters/axes.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/converters/ome_zarr.py, tiledb/bioimg/converters/openslide.py, tiledb/bioimg/converters/tiles.py, tiledb/bioimg/openslide.py
Follow-up to https://github.com/TileDB-Inc/TileDB-BioImaging/pull/48 to support chunked ingestion when the original axes are different from the saved (canonical) axes.
=> Chunked ingestion with axes transpositions

setup.py, tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/tiles.py
- Support parallel ingestion on multiple threads by passing a `max_workers` parameter.
- Display a progress bar during conversion (via [tqdm](https://github.com/tqdm/tqdm)): ![progressbar](https://user-images.githubusercontent.com/291289/208880824-dfe54b47-0040-4e79-b193-da468af1701a.gif)
=> Support multithreaded chunked ingestion

tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/openslide.py
Fix `OpenSlideReader.level_image` to pass the top left pixel in the **level 0 reference frame** as `location` to [OpenSlide.read_region](https://openslide.org/api/python/#openslide.OpenSlide.read_region), instead of the current level frame (as it was assumed).
**Note**: the current fix produces visually identical images to the original ones but [it is not 100% lossless for slide level greater than 0](https://github.com/openslide/openslide/issues/256) if `chunked=True`. If this is not acceptable, a user can select `chunked=False` (the default) or replace `OpenSlideConverter` with `OMETiffConverter`.
Example with the same slide converted (a) without chunking (b) with chunking on master (c) with chunking after this fix:
=> Fix OpenSlideReader.level_image for chunked conversion

tiledb/bioimg/converters/base.py
This PR:
- Add an extra group metadata key for tagging version of `tiledb.bioimg`. Now the group metadata of the converted images are ```{'axes': 'YXC', 'version': '0.1.1'}```
=> Inserting bioimg version in group metadata

tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tiledb/bioimg/openslide.py
Add a `TileDBOpenSlide.read_level` method for the (common) case of selecting a whole level image rather than a specific region with `read_region`.
=> Add TileDBOpenSlide.read_level

examples/OMETiff-convertor-demo.ipynb, examples/OMEZarr-convertor-demo.ipynb, tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tests/unit/test_openslide.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/openslide.py
This PR:
- extends the `TileDBOpenSlide` with a few new accessors:
- new properties: `levels`, `properties`, `original_axes`
- new method: `level_properties`
- new optional `to_original_axes` parameter for `read_level`/`read_level_dask`
- rewrites `ImageConverter.from_tiledb` to use the extended `TileDBOpenSlide` instead of raw tiledb-py to access the image data and metadata.
- deprecates  `TileDBOpenSlide.from_group_uri(uri)` in favor of `TileDBOpenSlide(uri)`.
=> Extend TileDBOpenSlide

tiledb/bioimg/converters/axes.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/openslide.py
First PR (out of 2) for webP support:
- Introduce optional `compressor` parameter in `ImageConverter.to_tiledb`. Defaults to the currently hardcoded value (`tiledb.ZstdFilter(level=0)`).
- Refactor code to pave the way for adding WebP. In particular, add a `get_pixel_depth()` function (better name suggestions are welcome) that returns the number of values encoded for each pixel. For non-webp compressors (i.e. this PR), this is always 1. For webP, the pixel depth will be determined by the selected colorspace format as described [here](https://github.com/TileDB-Inc/TileDB/blob/master/format_spec/filters/webp.md).
- Mostly unrelated but useful change: move the bulk of the `TileDBOpenSlide` functionality to a new `TileDBOpenSlideLevel` class and make the former essentially a sequence of the …
=> Allow custom compressor 

tiledb/bioimg/converters/base.py
- Follow up to https://github.com/TileDB-Inc/TileDB-BioImaging/pull/61 breaking down `ImageConverter.to_tiledb` into a few smaller more digestible functions.
- Replace `uri` with `name` in group level metadata.
=> Replace uri with member name in group metadata + DRY-fy base.py

tests/unit/test_axes.py, tiledb/bioimg/converters/axes.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/webp.py, tiledb/bioimg/openslide.py
- Replace the `ToWebPAxesMapper` and `FromWebPAxesMapper` subclasses of `AxesMapper` (introduced in https://github.com/TileDB-Inc/TileDB-BioImaging/pull/65) with:
1. `YXC_TO_YX`  and `YX_TO_YXC` subclasses of `Transform`
2. `Axes.webp_mapper` method to create the webp mapper from a given source axis.
- Unify the similar but separate APIs of `Transform` and `AxesMapper` and make the latter yet another subclass of the former.
- Rename `AxesMapper` to `CompositeAxesMapper`
- Rename `Transform` to `AxesMapper`
=> AxesMapper refactoring

tests/integration/converters/test_ome_zarr.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/helpers.py
Allow passing an existing `ImageReader` instance as `input_path` to `ImageConverter.to_tiledb`. 
Uses cases:
- Not having to create a `FooConverter` class for every `FooReader`; a user can call `ImageConverter.to_tiledb(FooReader(...), ...)` instead.
- In case one needs to convert the same input more than once (e.g. to both lossless and lossy output) and creating a `FooReader` is expensive, create only one instance and pass it to multiple `to_tiledb` calls.
Also some more `ImageConverter.to_tiledb` refactoring  while at it.
**Breaking Backwards Compatibility**: Breaking API `to_tiledb` with `source` argument instead of `input_path`
=> Allow passing ImageReader to `ImageConverter.to_tiledb`

tiledb/bioimg/converters/base.py
This PR:
- Fixes double group registration. The group creation with `tiledb` uri path already registers the group and there is no need for extra registration. It keeps the registration functionality when a uri except for `tiledb` is provided and when the `register_kwargs` are provided.
=> Fix double registration

.github/workflows/ci.yml, tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_scaler.py
This PR:
- Installs openslide from binaries in `win32` runner.
- Adds a `win32` CI. Now tests run in both `linux` and `win32`
=> Add windows runner CI

tests/integration/converters/test_ome_tiff.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/scale.py, tiledb/bioimg/helpers.py, tiledb/bioimg/openslide.py
This PR:
- Enables the user to ingest a multi-layer image by compressing each level with a separate filter.
- The default compression filter remains to be `Zstd` as it used to be.
- The user can either select a filter to be applied to all levels of the image `or` provide a mapping of levels -> filter for each image
- In the case of scaling an image with our `Scaler`, the newly constructed scaled levels are being compressed/filtered with the filter of the `base_layer`
-  In the metadata section due to this feature we have a change as now the `pixel_depth` value can differ among the different levels as it is a function of the filter that is used. We store this information in the group metadata as a Mapping as well.
- The changes were done in a way that the API of the `to_tiledb` does not …
=> Support different compressors per level

tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py
This PR:
- Fixes the behaviour of the `from_tiledb` API complementing https://app.shortcut.com/tiledb-inc/story/30787/vfs-write-to-s3-uri-fails-to-write. The VFS handle opens and close inside the function
=> Investigating exporting issue with VFS FileHandle

tests/integration/test_wrappers.py, tiledb/bioimg/__init__.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/wrappers.py
This PR:
- Creates a wrapper similar to `from_bioimg` #89 wrapper but this time for the export functionality. Utilizes the `to_tiledb` API
=> Exporter Wrapper to_bioimg

tiledb/bioimg/converters/base.py, tiledb/bioimg/helpers.py
This PR:
- Complements the investigation of [sc-30748] and it is a workaround for random access writes of `tifffile` dependency. This fix is OS specific.
=> TIFF Random Access Fix

tiledb/bioimg/converters/base.py
This PR:
- Removes the default dict value `{}` from `to_tiledb` to avoid future bugs. With the previous implementation the `reader_kwargs` and `tiles` where in `global_scope`, which could create issues.
=> Remove default initial value

.github/workflows/ci.yml
mamba-org/provision-with-micromamba is deprecated (https://github.com/mamba-org/provision-with-micromamba/pull/122)
Unfortunately it looks like selectors are no longer supported, so I installed `openslide` in a separate step
=> Migrate to mamba-org/setup-micromamba@v1

.github/workflows/ci.yml
This PR:
- Removes tests in CI for windows runners. The windows runners time out most of the times with bioimg tests leading to failing CI. There is no point in having these tests there just to see them fail due to resource/duration limitations. Let's silence them till we need them to test releases.
=> Increase runners timeout to fix windows CI job failure

tiledb/bioimg/converters/base.py, tiledb/bioimg/helpers.py, tiledb/bioimg/openslide.py
This PR:
- Adds two separate config args for exportation in case the destination has other access credentials needs than the source.
=> Add io separate configs for exportation

tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_zarr.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/converters/ome_zarr.py, tiledb/bioimg/converters/openslide.py, tiledb/bioimg/helpers.py, tiledb/bioimg/wrappers.py
In this PR:
- We introduce a logger in `tiledb-bioimg` package for easier debugging. The logging in the current commit is mostly focused on OMETiffConverter, Reader, Writer and the corresponding APIs. This initial implementation bootstraps the logging of other Converters as well. The logging messages for the rest converters will be added in following commits.
- Due to the dual nature of our API (Wrappers and Converter functions) we introduce for the wrappers an extra argument called `verbose`. This boolean when set to `True`, will enable DEBUG mode across the function calls and when `False` it will just behave in WARNING level debugging. 
- For the Converters API (consisting of `to_tiledb` and `from_tiledb`) we introduce an extra arg called `log` as a `Union[bool, logging.Logger]`. The …
=> Logger for tiledb-bioimg

setup.py
After the discussion https://tiledb.slack.com/archives/G01CJSR8G9H/p1695218069855349
I investigated the issue with 0-value arrays during chunk ingestion and it seems that the issue is known https://github.com/zarr-developers/zarr-python/issues/1497. This issue was fixed and released in version `2.16`. 
However for this upgrade to be applied I had to update our tifffile dependency from the pinned version `10.10.2022` to a later one.
The reason for pinning this `tifffile` version in the first place was that during the chunk ingestion of proprietary data, we were failing specifically on only these with a weird runtime `IndexError` reported here https://app.shortcut.com/tiledb-inc/story/30274/investigate-indexerror-from-zarrstore-when-chunked-true. 
Following up a discussion with the author …
=> Update tifffile version and unpin

.github/workflows/ci.yml, tests/__init__.py, tests/integration/converters/test_ome_tiff.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/helpers.py, tiledb/bioimg/wrappers.py
This PR:
- Adds an extra argument for excluding/including the original metadata of an image from the ingestion to TileDB.
- Adds tests to support the functionality above.
Additionally:
- Fixes CI test failing issues. The exit code of failing tests was not cascading to step's exit code as the output is piped to a file.
- Fixes failing tests for unsupported WEBP datatype on dims compression. As designed the WEBP does not support UINT32 datatypes so cannot be used for compressing dimensions in schema. The fix falls back to the default compressor ZSTD.
=> Exclude metadata from ingestion

tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/tiles.py, tiledb/bioimg/wrappers.py
This PR adds tiled writes to TileDB arrays during non chunked ingestion. This change allows non chunked ingestion to run directly against a TileDB uri, fixing the `Entity too Large` constraint in REST. To avoid small writes and achieve network saturation the write domain tile can be scaled to write larger amounts of data at once.
=> Tiled writes during ingestion

tiledb/bioimg/converters/ome_tiff.py
This PR fixes a bug where a duplicate channel ID will be written in case of an image a channel with multiple samples per pixel
=> Fix duplicate channel ID

.github/workflows/ci.yml, tiledb/bioimg/converters/__init__.py, tiledb/bioimg/converters/openslide.py
This PR:
- Changes python version from 3.7 to 3.9 in CI
- Changes tifffile patch for python version 3.7
- Removes edit mode from tiledb installation.
- Adds `WIN_OPENSLIDE_PATH` for supporting os.add_dll_directory() needed for python >=3.8 on Windows.
=> Python version in CI, no-edit mode for installed dependencies

.github/workflows/ci.yml, tiledb/bioimg/helpers.py
This PR:
- Adds a descriptive error in case of absence of `level` metadata key for a resolution layer.
- TileDB-Bioimaging supports incremental ingestion. In case of errors in previous runs for ingesting the specified image,
the default behaviour is that the same levels are not ingested from scratch. If THOUGH the previous run did not ingest correctly the image or was abruptly terminated then the image levels might have been already partially ingested. This will create an issue in case of missing metadata in the following run.
=> Add error for incomplete ingestion of previous image

setup.py
This PR:
- Adds the `jsonpickle` in the required dependencies since now it is used also in the `converters/base.py` module.
- Removes it from being a dependency only for `tiff` builds.
- Removes `tifffile` for being a required dependency. Now it is a dependency only for `tiff` and `full` builds.
=> Add jsonpickle to base dependencies

.pre-commit-config.yaml, README.md, setup.py, tiledb/bioimg/converters/ome_zarr.py
This PR:
- Adds version condition for accessing the `omero` channels metadata due to changes in `ome-zarr` in memory specification. The latest `0.9.0` release moves channels' name metadata under the key `"channel_names"` when before that the key was `name`.
- Require minimum version `0.9.0` for `ome-zarr`
=> Fix ome-zarr channels metadata access

tiledb/bioimg/converters/base.py
This PR:
- Updates the `dataset_type` metadata `kv` for Bioimg groups to avoid the race condition and the following misregistration as a simple Group, when canceling an ingestion mid-process.
=> Update dataset type early to avoid misregistration as simple Group

tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_openslide.py, tests/integration/converters/test_scaler.py, tests/integration/test_wrappers.py, tiledb/bioimg/converters/__init__.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/converters/ome_zarr.py, tiledb/bioimg/converters/openslide.py, tiledb/bioimg/helpers.py, tiledb/bioimg/openslide.py
This PR:
- Pushes down the VFS inside the converters allowing passing of config and context for accessing input images directly from S3. 
Usage:
```bash
from tiledb.bioimg import from_bioimg
from_bioimg(src='s3://tiledb-bioimg/local_testing/CMU-1-Small-Region-rgb.ome.tiff', dest='./tests/data/cmu-rgb-vfs.tdb', reader_kwargs={"config":tiledb.Config({})}
>>Ingesting level 0: 100%|██████████| 9/9 [00:00<00:00, 47.70tiles/s]
>>Ingesting level 1: 100%|██████████| 1/1 [00:00<00:00, 47.95tiles/s]
---
from tiledb.bioimg.openslide import TileDBOpenSlide
slide = TileDBOpenSlide('s3://tiledb-bioimg/local_testing/CMU-1-Small-Region-rgb.ome.tiff', config=tiledb.Config({}))
slide.levels
>>Out[9]: (0, 1, 2, 3)
```
It will resolve related story [sc-25684] [sc-43577]
=> Pushing VFS down to converters

setup.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/converters/ome_zarr.py, tiledb/bioimg/converters/openslide.py, tiledb/bioimg/wrappers.py
This PR:
- Fixes optional dependencies introducing guards in tiledb-bioimg API.
- Removes `tiledb-cloud` from the full installation. This will not affect our deployments in docker images or notebooks since the `tiledb-cloud-py` is already installed there. This will remove the warning - even though we were not importing the cloud-client anywhere- when a user is not logged in.
- Adding some warnings in case optional dependencies are missing.
- With all optional dependencies removed the user will face some warning but the `tiledb.bioimg` will be imported.
- Only when the user access the a Converter that relies on a dependency not present he gets a `ModuleNotFoundError`
```bash
In [1]: import tiledb.bioimg
/Users/konstantinostsitsimpikos/tiledb_dev/TileDB-BioImaging/./tiledb/bioimg/converters/ …
```
=> Fixing API dependencies guards and tiledb-cloud warning

.github/workflows/ci.yml
This PR:
- Removes the pin in CI for scikit-image after the release of version [`0.24.0`](https://pypi.org/project/scikit-image/0.24.0/) that supports `numpy==2.0`
=> Remove pinned scikit since 0.24.0 was released

tests/__init__.py, tests/unit/test_helpers.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/helpers.py
This PR:
- Introduces a helper function `validate_ingestion` that compares the `ned` and the number of fragments of each level with the `array schema` domains of each dimension to impose a correctness check.
- Till now once a level was created we were assuming its correctness without any check in order to support `incremental ingestion`. This logic however contradicted with the retry policy imposed during batch ingestion in taskgraph environment and led to missing metadata and errors like the following:
```python
File "tiledb/libmetadata.pyx", line 327, in tiledb.libtiledb.Metadata.__getitem__
KeyError: 'level'
```
-  Tests the validation function's internals in unittest.
=> Validating ingestion of levels to make ingestion idempotent

.github/workflows/ci.yml, README.md, tiledb/bioimg/converters/__init__.py
This PR:
- Changes the installation path of `openslide` for Windows from `D:/` to `C:`
=> Change Openslide Drive Path for Windows

tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/converters/ome_zarr.py, tiledb/bioimg/converters/openslide.py, tiledb/bioimg/wrappers.py
This PR:
- Adds support for separate source `config` and destination `config` for the ingestion.
**Depends on `tiledb-py==0.30.3` release**
=> Support source dest configs ingestion

setup.py, tests/integration/converters/__init__.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tiledb/bioimg/__init__.py, tiledb/bioimg/converters/__init__.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/converters/ome_zarr.py, tiledb/bioimg/converters/openslide.py, tiledb/bioimg/plugin_manager.py, tiledb/bioimg/wrappers.py
This PR:
- Modifies the `ImageReader` and `ImageWriter` from using abstract base classes to use protocols. This will allow third-party plugins to define `ImageReader` and `ImageWriter` classes without importing `TileDB-BioImaging`.
=> Convert ABC base classes to Protocols

tests/__init__.py, tests/unit/test_helpers.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/helpers.py
Problem statement:
You can find it in the shortcut ticket.
This PR:
- Parses the OME-XML metadata and instead of removing it as a whole it removes only the metadata for the `macro` and `label` images. Leaving the OME-XML metadata structure solves the issue with Qupath and the latter can select the correct reader for rendering an exported image.
=> Exported images fail to render in qupath

tests/integration/converters/test_ome_tiff.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/helpers.py
This PR:
- Adds a metadata KV at a group level of an ingested image signalling if the ingestion was completed successfully after all the steps.
- The metadata key `valid` gets a boolean value of either `True` or `False`
- During every ingestion a check is being performed to find if the desination path already exists and is a group. In this scenario we check if the group's metadata contain the key `valid`. If not this signals a corrupted ingested file (possibly from a previous run) and the response to that is for the group to be overwritten from scratch.
- In case the group exists but the ingestion runs in order for more layers to be added into the image `incremental ingestion` the flag is not enabled. We initially remove again the `valid` KV from the group's metadata until re-instantiate …
=> Adding a metadata flag for signaling successful ingestion

tiledb/bioimg/converters/io.py
Previously the experimental reader was erroneously detecting missing dimension as complete when checking for which chunks to write during ingestion. This PR addresses that and skip those missing dimensions.
=> Experimental reader dimension detection hotfix

tiledb/bioimg/helpers.py
This PR:
- Fixes an overlook of closing a Group in `modify mode` during context exit,  in order to eliminate any possible implication this may have to the group's deletion.
=> Close group variant for Group deletion

tests/__init__.py, tests/integration/converters/test_ome_tiff.py, tests/integration/converters/test_ome_tiff_experimental.py, tests/integration/converters/test_ome_zarr.py, tests/integration/converters/test_openslide.py, tests/integration/converters/test_png.py, tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/converters/ome_zarr.py, tiledb/bioimg/converters/openslide.py, tiledb/bioimg/converters/png.py, tiledb/bioimg/helpers.py
In https://github.com/TileDB-Inc/TileDB-BioImaging/pull/147, the import of `WebpInputFormat` type was changed from `from tiledb.cc import WebpInputFormat` to `from tiledb.libtiledb import WebpInputFormat`, as https://github.com/TileDB-Inc/TileDB-Py/pull/2123 renamed `cc` to `libtiledb`. This change caused backward compatibility issues. 
To resolve the issue, this PR uses the exposed type instead of the internal one. 
Furthermore, to generally address similar issues without requiring code changes, an alias has been provided: https://github.com/TileDB-Inc/TileDB-Py/pull/2145.
=> Use exposed type instead of internal

.github/workflows/ci.yml
This PR:
- Updates the ubuntu version of CI runners due to upcoming deprecation as noted [actions/runner-images#11101](https://github.com/actions/runner-images/issues/11101).
=> Updating runner's ubuntu version due to deprecation

tests/unit/test_axes.py, tiledb/bioimg/converters/axes.py
This PR:
- Changes the internal management of custom named axes. Instead of raising `ValueError` when axes names do not fall under the canonical axes names' convention, we now rename this custom axis to a `standard` axis name that is available excluding the required axes names `X`, `Y` and `C`. If there is no availability then we throw the error.
The behaviour is bounded to support cases up to 5D images, as it is already supported. With a future change we want to totally decouple the axes names from the need of following a canonical convention.
=> Transforming custom axes to canonical up to 5D

tiledb/bioimg/converters/ome_tiff.py
This PR:
- Modifies the `subifds` argument in the ome-tiff writer so it can produce `generic-tiffs` which are openslide-compatible.
OME-TIFF are not compatible with OpenSlide https://github.com/cgohlke/tifffile/issues/159
=> Support generic tiff

.github/workflows/ci.yml, tiledb/bioimg/plugin_manager.py
This PR:
- Introduces conditional function calls to `importlib.metadata` library according to the python version.
- Adds a CI job for running CI with `python 3.12` too.
=> Python 3.12 issue resolution and CI enrichment

tiledb/bioimg/converters/base.py, tiledb/bioimg/converters/ome_tiff.py, tiledb/bioimg/converters/ome_zarr.py, tiledb/bioimg/converters/png.py
This PR:
- Allows extra arguments to be passed into the converters constructor.
=> Fix writer constructor tiff options arguments
